### PR TITLE
Setup AppVeyor build

### PR DESCRIPTION
**Pull request by dungpa**
Try to reproduce test errors when only VS 2013 is available.

### CODE REVIEW

**Comment by dungpa** [comment]
@FeodorFitsner Why does the 'Windows Server 2012 R2' image have VS 2015 assemblies installed? I try to reproduce test errors if only VS 2013 is available. The tests pass on 'Windows Server 2012 R2' image but fail on 'Previous Windows Server 2012 R2' image (as expected).

Is 'Previous Windows Server 2012 R2' image stable for use?

**Comment by FeodorFitsner** [comment]
For OSS accounts default `Windows Server 2012 R2` image has always been with VS 2015 installed. Why would you need running it on "Previous"?

**Comment by dungpa** [comment]
I need an isolated environment of VS 2013 without VS 2015 installed. It would help reproduce the errors of the project because it has (wrong) dependencies on VS 2015. Thanks.

**Comment by FeodorFitsner** [comment]
Fair enough. I've added a new `Visual Studio 2013` image which allows you explicitly target VS 2013.

**Comment by dungpa** [comment]
@FeodorFitsner It works. Thanks for the great help.

**Pull request merged**
