### PR TITLE
Upgraded packages to their latest versions.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
This PR actually solves #213 for which there is a non-trivial workaround. Specifically,

- [x] Upgraded FSharp.Core to the latest version (4.2.3).
- [x] Upgraded FSharp.Compiler.Services to the latest version (16.0.2).
- [x] The unit testing framework is updated to NUnit 3.8.1.

However, when running the unit tests, fail into this mysterious error:

```
1) Invalid : C:\code\fantomas\src\Fantomas.Tests\bin\Release\Fantomas.Tests.dll
Δεν είναι δυνατή η φόρτωση ενός ή περισσότερων απαιτούμενων τύπων. Για περισσότερες πληροφορίες, απαιτείται ανάκτηση της ιδιότητας LoaderExceptions.
  ----> Δεν είναι δυνατή η φόρτωση του αρχείου ή της συγκρότησης 'FSharp.Core, Version=3.7.41.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ή σχετικής εξάρτησης. Ο εντοπισμένος ορισμός διακήρυξης της συγκρότ
ησης δεν αντιστοιχεί στην αναφορά συγκρότησης. (Εξαίρεση από HRESULT: 0x80131040)
```

> Approximate translation: [`The located assembly's manifest definition does not match the assembly reference`](https://stackoverflow.com/questions/93879/hresult-0x80131040-the-located-assemblys-manifest-definition-does-not-match-t).

I might need some help with this one. And another task must be declared:

- [x] The unit tests run.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
Looks like the tests only fail on Windows.

**Comment by dungpa** [comment]
Seem like an environmental issue. Could you try with a new AppVeyor image than https://github.com/dungpa/fantomas/blob/f51bf728c428539e066b1227f5c7ec7ac01bf556/appveyor.yml#L1?

**Comment by teo-tsirpanis** [comment]
No luck.

**Comment by danyx23** [comment]
I'd like to help with this and start contributing to Fantomas. I managed to get your branch to compile on Windows with VS 2017 (15.5.7) with all tests working (and 2 being ignored) if I change the assembly binding redirect for the tests and cmd app in the app.config to:
```
<dependentAssembly>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.1.0" />
</dependentAssembly>
```

Can you check if it works for you if you do this, @teo-tsirpanis ? I don't have a deep understanding of the binding redirects, 4.4.1.0 seems to be the FSharp.Core version that is chosen by Paket for my system so that is what I entered above (Nuget package version 4.2.3)

**Comment by teo-tsirpanis** [comment]
Appveyor now passes. @dungpa, can we merge?

**Comment by teo-tsirpanis** [comment]
Fantomas still doesn't work with updated packages.

I give up. 🙌

**Pull request closed without merging**
