### PR TITLE
Migrate to dotnet core

### PR DESCRIPTION
**Pull request by nojaf**
We hope to get more people involved in this project by migrating it to dotnet core 2.0.
All projects currently build and you can run the tests (but 5 fail).

Todo:
- [X] Create new dotnet core projects and reference existing files
- [X] Update all paket dependencies to latest
- [X] Fix failing unit tests *
- [x] Add support for full framework
- [x] Update `build.fsx` script (Fake 5 stable?)
- [x] Setup continuous integration
- [x] Change Cmd.Core to be a `clitool`, so that `dotnet fantomas` works
- [x] Remove the old projects

** unit test output
```
PS C:\Users\nojaf\Projects\fantomas\src\Fantomas.Tests.Core> dotnet test .\Fantomas.Tests.Core.fsproj
Build started, please wait...
C:\Users\nojaf\Projects\fantomas\src\Fantomas.Tests\SpecialConstructsTests.fs(16,4): warning FS0988: Main module of program is empty: nothing will happen when it is run [C:\Users\nojaf\Projects\fantomas\src\Fantomas.Tests.Core\Fantomas.Tests.Core.fsproj]
Build completed.

Test run for C:\Users\nojaf\Projects\fantomas\src\Fantomas.Tests.Core\bin\Debug\netcoreapp2.0\Fantomas.Tests.Core.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.10.0.21: Test execution started
Running all tests in C:\Users\nojaf\Projects\fantomas\src\Fantomas.Tests.Core\bin\Debug\netcoreapp2.0\Fantomas.Tests.Core.dll
NUnit3TestExecutor converted 285 of 285 NUnit test cases
Skipped  should align mis-aligned comments
Error Message:
 reason

Skipped  should keep comments on else if
Error Message:
 reason

NUnit Adapter 3.10.0.21: Test execution complete

Total tests: 285. Passed: 283. Failed: 0. Skipped: 2.
Test Run Successful.
Test execution time: 7.5011 Seconds
```

Please let me know if I'm missing anything.

### CODE REVIEW

**Comment by nojaf** [comment]
Hijacking this thread to talk about one of the failing tests:

>dotnet test .\Fantomas.Tests.Core.fsproj --filter "should keep compiler directives 2"

```fsharp
[<Test>]
let ``should keep compiler directives 2``() =
    formatSourceString false """
#if INTERACTIVE
#else
#load "../FSharpx.TypeProviders/SetupTesting.fsx"
SetupTesting.generateSetupScript __SOURCE_DIRECTORY__
#load "__setup__.fsx"
#endif
"""  config
    |> fun fss -> 
        printfn "%s" fss
        fss 
    |> should equal """
#if INTERACTIVE
#else
#load "../FSharpx.TypeProviders/SetupTesting.fsx"
SetupTesting.generateSetupScript __SOURCE_DIRECTORY__
#load "__setup__.fsx"
#endif
"""
```

The result of the printfn is:

```fsharp
 #if INTERACTIVE

 #else

 #load "../FSharpx.TypeProviders/SetupTesting.fsx"
 SetupTesting.generateSetupScript __SOURCE_DIRECTORY__
 #load "__setup__.fsx"
 #endif

 #load "../FSharpx.TypeProviders/SetupTesting.fsx"

 SetupTesting.generateSetupScript __SOURCE_DIRECTORY__

 #load "__setup__.fsx"
```

The piece inside the else block is printed twice. This is because the `#if INTERACTIVE` returns false and the else block is parsed by the FCS and is visible inside the ast.
To something like this

```fsharp
[SynModuleOrNamespace
   ([Program],false,true,
    [HashDirective
       (ParsedHashDirective
          ("load",["../FSharpx.TypeProviders/SetupTesting.fsx"],
           Program.fs (3,0--3,49) IsSynthetic=false),
        Program.fs (3,0--3,49) IsSynthetic=false);
     DoExpr
       (SequencePointAtBinding Program.fs (4,0--4,53) IsSynthetic=false,
        App
          (NonAtomic,false,
           LongIdent
             (false,
              LongIdentWithDots
                ([SetupTesting; generateSetupScript],
                 [Program.fs (4,12--4,13) IsSynthetic=false]),None,
              Program.fs (4,0--4,32) IsSynthetic=false),
           Const
             (String
                ("C:\Users\nojaf\Projects\fantomas\src",
                 Program.fs (4,33--4,53) IsSynthetic=false),
              Program.fs (4,33--4,53) IsSynthetic=false),
           Program.fs (4,0--4,53) IsSynthetic=false),
        Program.fs (4,0--4,53) IsSynthetic=false);
     HashDirective
       (ParsedHashDirective
          ("load",["__setup__.fsx"],Program.fs (5,0--5,21) IsSynthetic=false),
        Program.fs (5,0--5,21) IsSynthetic=false)],PreXmlDocEmpty,[],None,
    Program.fs (3,0--5,21) IsSynthetic=false)]
```

The fantomas context for this (created by `Fantomas.FormatConfig.Context.create`) is:

```fsharp
{Config = {IndentSpaceNum = 4;
            PageWidth = 80;
            SemicolonAtEndOfLine = false;
            SpaceBeforeArgument = true;
            SpaceBeforeColon = true;
            SpaceAfterComma = true;
            SpaceAfterSemicolon = true;
            IndentOnTryWith = false;
            ReorderOpenDeclaration = false;
            SpaceAroundDelimiter = true;
            StrictMode = false;};
  Writer = Fantomas.FormatConfig+ColumnIndentedTextWriter;
  BreakLines = true;
  BreakOn = <fun:get_Default@136>;
  Content =
   "
 #if INTERACTIVE
 #else
 #load "../FSharpx.TypeProviders/SetupTesting.fsx"
 SetupTesting.generateSetupScript __SOURCE_DIRECTORY__
 #load "__setup__.fsx"
 #endif
 ";
  Positions = [|0; 1; 17; 23; 73; 127; 149; 156; 157|];
  Comments = seq [];
  Directives = seq [];}
```

Because the content contains everything it kinda adds up to why we are seeing the the `#else` block twice. This behavior could be introduced due to the introduction of a newer FCS.
I'll check with the original code to see if the output prints are the same or not.

**Comment by nojaf** [comment]
Turns out it was a configuration problem indeed, unit tests are now fixed.

**Comment by danyx23** [comment]
Hi nojaf - this looks very promising, do you need help? I'd like to get Fantomas building/working under .net core and then start contributing small fixes. I saw that the main program executable is not yet implemented again, what are your plans here and can I help somehow?

**Comment by nojaf** [comment]
Hi @danyx23 , you could try the [artifacts on AppVeyor](https://ci.appveyor.com/project/dungpa/fantomas/build/99/artifacts). That part is almost done, we are facing some [warnings on the full framework](https://ci.appveyor.com/project/dungpa/fantomas/build/99#L313) side of things.
Basically it should work if you download the artifacts and try installing fantomas as a clitool.

Add `<add key="fantomas-core" value="C:\YourFolderWithLocalPackages" />`
to `"C:\Users\You\AppData\Roaming\NuGet\NuGet.Config"`

Then in a `fsproj` you can add `<DotNetCliToolReference Include="dotnet-fantomas" Version="2.7.0" />`. Do a `dotnet restore` and try running `dotnet fantomas "myfile.fs"`.

If you have any ideas regarding the full framework warnings, we are all ears.

**Comment by nojaf** [comment]
@dungpa could you please review this? We think it is finished and can be released.

**Comment by nojaf** [comment]
@dungpa many thanks for the merge! Let us know if it needs any more changes in order to be published on nuget.

**Comment by dungpa** [comment]
@nojaf I have some problems with NuGet keys (couldn't push new packages). 

Could I add you as a NuGet owner for pushing packages? If you agree, please give me your NuGet user name. Thanks.

**Comment by nojaf** [comment]
Thanks, my name is also **nojaf**.

**Comment by dungpa** [comment]
I sent the owner request. Thanks again both.

**Comment by ErikSchierboom** [comment]
Great work! Any chance that the docs will be updated too? :)

**Comment by nojaf** [comment]
I'm planning to do this once it is all ok on NuGet, please try https://www.nuget.org/packages/dotnet-fantomas/2.7.1 and let me know. I'm also working on blog post regarding these changes.

**Comment by ErikSchierboom** [comment]
@nojaf I've just tested it, working fine! Thanks!

**Comment by danyx23** [comment]
Very cool, thank you all for your work!

**Pull request merged**
